"""Export the Core's labels for separately assembled overlays (BBS).

Reads build/disk_main.vs (VICE labels of the main assembly) and writes
build/core_syms.inc with `.label name = $addr` for every Core label that a
separate overlay may call or use. Left out:
  - labels in the overlay area $8000-$BFFF (other overlays),
  - names that occur more than once (local labels such as lp/done),
  - names the overlay defines itself (its own sources, net/*, include/*).
The Core and the cartridge build have identical addresses (main_cart pads
its image to $0810), so the same file serves both.
"""
import re, sys, glob, os

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
vs = os.path.join(root, 'build', 'disk_main.vs')
out = os.path.join(root, 'build', 'core_syms.inc')
own_sources = sys.argv[1:] or ['net/*.asm', 'net/*.inc', 'apps/bbs/*.asm', 'apps/email/*.asm',
                               'apps/email/*.inc', 'include/*.inc', 'bbs_main.asm', 'email_main.asm']

defined = set()
pat = re.compile(r'^\s*(?:\.label\s+|\.const\s+|\.var\s+)?([A-Za-z_]\w*)\s*(?::|=)', re.M)
for g in own_sources:
    for f in glob.glob(os.path.join(root, g)):
        for m in pat.finditer(open(f, encoding='utf-8', errors='replace').read()):
            defined.add(m.group(1))

seen = {}
for line in open(vs, encoding='utf-8'):
    m = re.match(r'al C:([0-9a-f]+) \.(\S+)', line)
    if not m:
        continue
    addr, name = int(m.group(1), 16), m.group(2)
    seen.setdefault(name, set()).add(addr)

lines = []
for name, addrs in sorted(seen.items()):
    if len(addrs) != 1 or name in defined or not re.match(r'^[A-Za-z_]\w*$', name):
        continue
    addr = next(iter(addrs))
    if 0x8000 <= addr < 0xC000:
        continue
    lines.append('.label %s = $%04x' % (name, addr))

with open(out, 'w', encoding='utf-8') as f:
    f.write('// generated by tools/export_core_syms.py - do not edit\n#importonce\n')
    f.write('\n'.join(lines) + '\n')
print('%d core labels -> %s' % (len(lines), out))
